name: Documentation

on:
  push:
    branches:
      - master         # Push events on master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v2
      with:
        token: ${{ secrets.DEPLOY_DOC_PAT }}
        repository: devitocodes/devitoproject.org
        event-type: deploy-docs